### ISSUE TITLE
Initialization failed after upgrading to 1.4.3

### ISSUE THREAD

**Issue by cybervedaa** [elasticsearch/elasticsearch#9684]
I just upgraded Elasticsearch from 1.4.2 to 1.4.3. Now ES wont start up. I installed it by extracting the TAR file. 
I found this in the logs :
[2015-02-12 17:48:00,509][ERROR][bootstrap                ] {1.4.3}: Initialization Failed ...
- NoSuchMethodError[org.apache.lucene.util.automaton.MinimizationOperations.minimize(Lorg/apache/lucene/util/automaton/Automaton;)Lorg/apache/lucene/util/automaton/Automaton;]

Java version 1.7.0_67
Centos 6.6 x86_64

The elasticsearch build number is 36a29a7/2015-02-11T14:23:15Z

**Comment by cybervedaa** [comment]
I enabled TRACE int the logs and now i get the full stacktrace. It looks like the unavailable method is being called by Shield. I am using Shield 1.0.0. Is there a newer version of Shield available?
Below is my stack trace :

[2015-02-12 18:17:15,696][ERROR][bootstrap                ] {1.4.3}: Initialization Failed ...
- NoSuchMethodError[org.apache.lucene.util.automaton.MinimizationOperations.minimize(Lorg/apache/lucene/util/automaton/Automaton;)Lorg/apache/lucene/util/automaton/Automaton;]
java.lang.NoSuchMethodError: org.apache.lucene.util.automaton.MinimizationOperations.minimize(Lorg/apache/lucene/util/automaton/Automaton;)Lorg/apache/lucene/util/automaton/Automaton;
        at org.elasticsearch.shield.support.Automatons.patterns(Automatons.java:67)
        at org.elasticsearch.shield.support.Automatons.patterns(Automatons.java:49)
        at org.elasticsearch.shield.authz.Privilege$System.<clinit>(Privilege.java:95)
        at org.elasticsearch.shield.authz.Privilege.<clinit>(Privilege.java:54)
        at org.elasticsearch.shield.action.ShieldActionFilter.<clinit>(ShieldActionFilter.java:52)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
        at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:59)
        at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:197)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:70)
        at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:203)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)

**Comment by jaymode** [comment]
@cybervedaa thanks for your report. We're working on the incompatibility with Shield and 1.4.3. A fix is coming shortly.

**Comment by zhufeizzz** [comment]
Same issue, when fix package come out, please give a notice, tks

**Comment by jaymode** [comment]
Shield 1.0.1 has been released with the fix. Please see http://www.elasticsearch.org/blog/shield-1-0-1-released/
